# Generated by Django 4.2.27 on 2026-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardfeedback',
            new_name='core_dashbo_created_1a3a85_idx',
            old_name='core_dashbo_created_2dca2f_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardfeedback',
            new_name='core_dashbo_section_152fd2_idx',
            old_name='core_dashbo_section_f5a0fc_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardfeedback',
            new_name='core_dashbo_reporte_a01e58_idx',
            old_name='core_dashbo_reporte_25f530_idx',
        ),
    ]
