# Generated by Django 4.2.27 on 2026-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_dashbo_created_2dca2f_idx_core_dashbo_created_1a3a85_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Stručný názov')),
                ('description', models.TextField(verbose_name='Popis úlohy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
            ],
            options={
                'verbose_name': 'TODO úloha',
                'verbose_name_plural': 'TODO úlohy',
                'ordering': ('-created_at',),
            },
        ),
    ]
