# Generated by Django 4.2.27 on 2026-01-30 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('scoring_rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='competitions.competition')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='competition_token_d9d256_idx'), models.Index(fields=['competition', 'used_at'], name='competition_competi_f56e5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZER', 'Organizer'), ('CONTESTANT', 'Contestant')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['competition', 'role'], name='competition_competi_263aee_idx'), models.Index(fields=['user'], name='competition_user_id_e01c3c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionmembership',
            constraint=models.UniqueConstraint(fields=('competition', 'user'), name='uniq_membership_competition_user'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['starts_at'], name='competition_starts__7183aa_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['ends_at'], name='competition_ends_at_ce9dd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='competition_ends_after_starts'),
        ),
    ]
