# Generated by Django 4.2.27 on 2026-02-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_tier'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='competition_competi_f245b8_idx',
            old_name='competitions_invitation_comp_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='invitationuse',
            new_name='competition_invitat_76632e_idx',
            old_name='competitions_invitation_inv_created_6d0a92_idx',
        ),
        migrations.RenameIndex(
            model_name='invitationuse',
            new_name='competition_user_id_050504_idx',
            old_name='competitions_invitation_use_user_created_5f5a6c_idx',
        ),
        migrations.AddField(
            model_name='competitionmembership',
            name='spot_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='competitionmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('spot_number__isnull', False)), fields=('competition', 'spot_number'), name='uniq_membership_competition_spot_number'),
        ),
    ]
