# Generated by Django 4.2.27 on 2026-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_invitation_spot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionmembership',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizátor'), ('CONTESTANT', 'Súťažiaci')], max_length=20),
        ),
    ]
