# Generated by Django 4.2.27 on 2026-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competitionmembership_is_organizer_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'permissions': [('premium', 'Premium')]},
        ),
        migrations.RenameIndex(
            model_name='competitionmembership',
            new_name='competition_competi_6d00b1_idx',
            old_name='comp_membership_comp_org_idx',
        ),
    ]
