# Generated by Django 4.2.27 on 2026-01-30 13:08

import apps.catches.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=120)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('caught_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to=apps.catches.models.catch_photo_upload_to)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='competitions.competition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['competition', 'status', 'created_at'], name='catches_cat_competi_b36d15_idx'), models.Index(fields=['user', 'created_at'], name='catches_cat_user_id_97811f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='catch',
            constraint=models.CheckConstraint(check=models.Q(('length_cm__isnull', True), ('length_cm__gt', 0), _connector='OR'), name='catch_length_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='catch',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__isnull', True), ('weight_kg__gt', 0), _connector='OR'), name='catch_weight_positive_or_null'),
        ),
    ]
