# Generated by Django 4.2.27 on 2026-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_catch_photo_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Body získané za úlovok', max_digits=8),
        ),
    ]
