# Generated by Django 4.2.27 on 2026-02-06 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined")], db_index=True, default="PENDING", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by", models.ForeignKey(help_text="Kto poslal žiadosť", on_delete=django.db.models.deletion.CASCADE, related_name="friendships_requested", to=settings.AUTH_USER_MODEL)),
                ("user_a", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friendships_a", to=settings.AUTH_USER_MODEL)),
                ("user_b", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="friendships_b", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="friends_fri_status_6102af_idx"),
                    models.Index(fields=["user_a", "status"], name="friends_fri_user_a_8dc28e_idx"),
                    models.Index(fields=["user_b", "status"], name="friends_fri_user_b_1cf294_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("user_a", "user_b"), name="uniq_friendship_pair"),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(check=models.Q(("user_a", models.F("user_b")), _negated=True), name="friendship_not_self"),
        ),
    ]
