# Generated by Django 4.2.27 on 2026-02-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friends_fri_status_4ee2c3_idx',
            old_name='friends_fri_status_6102af_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friends_fri_user_a__4c6dcd_idx',
            old_name='friends_fri_user_a_8dc28e_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friends_fri_user_b__324b72_idx',
            old_name='friends_fri_user_b_1cf294_idx',
        ),
    ]
