# Generated by Django 4.2.27 on 2026-06-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CATCH_CREATED', 'Catch created'), ('CATCH_APPROVED', 'Catch approved'), ('CATCH_REJECTED', 'Catch rejected'), ('FRIEND_REQUEST', 'Friend request'), ('FRIEND_ACCEPTED', 'Friend accepted'), ('COMP_CANCELLED', 'Competition cancelled'), ('ORGANIZER_PROMOTED', 'Organizer promoted'), ('COMP_ADDED', 'Added to competition'), ('OVERTAKEN', 'Overtaken on scoreboard')], max_length=40),
        ),
    ]
